
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/logs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.projectriff.io
  resources:
  - containers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - task.projectriff.io
  resources:
  - taskexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.projectriff.io
  resources:
  - taskexecutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - task.projectriff.io
  resources:
  - tasklaunchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.projectriff.io
  resources:
  - tasklaunchers/status
  verbs:
  - get
  - patch
  - update
