
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - task.projectriff.io
  resources:
  - taskexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.projectriff.io
  resources:
  - taskexecutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - task.projectriff.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.projectriff.io
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
